name: pro
services:
  gateway: true
  control: true
  console: true
features:
  mlflow:
    enabled: true
  jupyter:
    enabled: true
  docker:
    enabled: true
  k8s:
    enabled: false
  ldap:
    enabled: false
security:
  hardening:
    level: standard
