[package]
name = "execution"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
wasmtime = "14"
wat = "1"
ring = "0.17"
rand = "0.8"
parking_lot = "0.12"

serde_json = "1"
