global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
  - job_name: 'gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:9464']
  - job_name: 'control'
    metrics_path: /metrics
    static_configs:
      - targets: ['control:9464']
